services:
  - type: web
    name: traffic-simulator
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python iot_simulator.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0